### ISSUE TITLE
Exception on newest version of elasticsearch

### ISSUE THREAD

**Issue by odmarkj** [jeskew/amazon-es-php#5] opened 2017-11-08 18:26 UTC
v5.3.2 causes a "Host must be a string" to be thrown.

```
$provider = CredentialProvider::fromCredentials(
    new Credentials($_SERVER['AWS_ACCESS_KEY_ID'], $_SERVER['AWS_SECRET_KEY'])
);

$handler = new ElasticsearchPhpHandler($_SERVER['AWS_REGION'], $provider);

$client = ClientBuilder::create()
                ->setHandler($handler)
                ->setHosts(['https://url.com:443'])
                ->build();

$results = $client->search($params);
```

Reverting to v5.3.0 fixes the issue.

This just started happening a few days ago.

I may eventually submit a PR for a fix, but don't have the time right now.

**Comment by farnsworthMars** [comment] 2017-11-09 05:50
I saw the same thing - added this to my composer.json require block to lock elasticsearch/elasticsearch to 5.3.0 and the problem went away.  
```"elasticsearch/elasticsearch": "5.3.0",```

**Comment by jeskew** [comment] 2017-11-09 06:26
This looks like it was caused by [this change](https://github.com/elastic/elasticsearch-php/commit/1621094).

**Comment by rafaeltovar** [comment] 2017-11-09 09:47
The same for me. With `elasticsearch/elasticsearch` `5.3.0` works correctly, but not with `5.3.1`.

**Comment by rafaeltovar** [comment] 2017-11-09 11:00
I did a pull request with fix. 
https://github.com/jeskew/amazon-es-php/pull/6

**Comment by jeskew** [comment] 2017-11-16 02:23
Fixed in #6

**Closed as completed by jeskew** 2017-11-16 02:23 UTC
